export type Sport = 'Football' | 'Cricket' | 'Basketball' | 'Running';
export type Level = 'Beginner' | 'Intermediate' | 'Advanced';
export type Athlete = { name: string; sport: Sport; level: Level; position: string; goals: string[]; preferences: string[] };
export type Drill = { id: string; name: string; sport: Sport; type: string; minutes: number; intensity: 'Easy' | 'Moderate' | 'Hard'; description: string; focus: string; equipment: string[] };
export type Workout = { id: string; title: string; sport: Sport; minutes: number; level: Level; focus: string; calories: number; steps: { name: string; seconds: number; cue: string }[] };
export type Goal = { id: string; title: string; metric: string; target: number; current: number; unit: string; due: string; milestones: { label: string; done: boolean }[] };
export type SocialPost = { id: string; author: string; handle: string; role: string; initials: string; color: string; text: string; time: string; likes: number; comments: number; liked?: boolean; following?: boolean; tags: string[] };
export type Match = { id: string; teams: string; league: string; sport: Sport; time: string; status: 'LIVE' | 'UPCOMING'; viewers: string; venue: string };

const drillNames = [
  ['First-step acceleration', 'Speed', 'Sprint mechanics off the mark'], ['Lateral shuffle gates', 'Agility', 'Own the first two steps side to side'], ['Single-leg pogo hops', 'Elasticity', 'Build spring without losing stiffness'], ['Deceleration drops', 'Control', 'Brake cleanly from top speed'], ['Hip lock march', 'Mobility', 'Stack hip, knee, ankle under load'], ['Ankle rocker series', 'Mobility', 'Open the ankle for better positions'], ['Split squat iso hold', 'Strength', 'Own the bottom range'], ['Copenhagen plank', 'Core', 'Train adductor resilience'], ['Nordic hamstring lower', 'Strength', 'Protect your high-speed engine'], ['Broad jump stick', 'Power', 'Project force and land quietly'],
  ['Cone reaction call', 'Reaction', 'React to the visual cue'], ['Mirror shuffle', 'Agility', 'Match your partner with soft feet'], ['Cross-body reach', 'Coordination', 'Connect trunk and hips'], ['A-skip rhythm', 'Technique', 'Dial in knee lift and posture'], ['Wall drive switches', 'Technique', 'Feel the correct sprint angle'], ['Calf raise tempo', 'Strength', 'Build lower-leg capacity'], ['Dead bug press', 'Core', 'Brace while limbs move'], ['Bear crawl reach', 'Coordination', 'Move with opposite hand and foot'], ['Medicine ball scoop', 'Power', 'Transfer force through the hips'], ['Rotational throw', 'Power', 'Turn speed into release speed'],
  ['Box breathing reset', 'Recovery', 'Downshift your nervous system'], ['90/90 flow', 'Mobility', 'Move through hip rotation'], ['T-spine windmill', 'Mobility', 'Free your upper back'], ['Hamstring floss', 'Recovery', 'Keep posterior chain moving'], ['Glute bridge march', 'Activation', 'Wake up the hips'], ['Scap push-up', 'Activation', 'Own your shoulder blades'], ['Plank shoulder tap', 'Core', 'Resist rotation'], ['Single-leg RDL reach', 'Balance', 'Build foot and hip control'], ['Tempo push-up', 'Strength', 'Create tension through every rep'], ['Bodyline hollow hold', 'Core', 'Connect ribs to pelvis'],
  ['Fast feet line', 'Footwork', 'Short contacts, quiet upper body'], ['Drop step turn', 'Footwork', 'Open the hips on demand'], ['Carioca flow', 'Coordination', 'Find rhythm through the hips'], ['Reactive split step', 'Reaction', 'Load before you move'], ['Sprint-float-sprint', 'Speed', 'Change gears with intent'], ['Hill march', 'Strength', 'Build drive without overstriding'], ['Jump rope cadence', 'Conditioning', 'Hold a steady elastic rhythm'], ['Tempo run builder', 'Conditioning', 'Progress from easy to controlled'], ['Breathing jog', 'Recovery', 'Keep your aerobic work relaxed'], ['Cool-down walk', 'Recovery', 'Bring your system back down'],
] as const;
export const drills: Drill[] = drillNames.map((d, i) => ({ id: `d${i + 1}`, name: d[0], type: d[1], focus: d[2], sport: (['Football', 'Cricket', 'Basketball', 'Running'] as Sport[])[i % 4], minutes: 6 + (i % 5) * 3, intensity: i % 3 === 0 ? 'Hard' : i % 3 === 1 ? 'Moderate' : 'Easy', description: `${d[2]}. Keep quality high and stop one rep before form drops.`, equipment: i % 4 === 0 ? ['Cones'] : i % 4 === 1 ? ['Mini band'] : i % 4 === 2 ? ['None'] : ['Medicine ball'] }));

const workoutTitles = ['Game-day Primer', 'Explosive First Step', 'Full Body Athletic Base', 'Match Engine', 'Shoulder Armor', 'Tempo & Turnover', 'Lower Body Power', 'Reactive Footwork', 'Aerobic Builder', 'Recovery Reset', 'Core Under Pressure', 'Speed Mechanics', 'Jump & Land', 'Strength Circuit', 'Ball-ready Warmup', 'Weekend Long Run', 'Change of Direction', 'Match Simulation', 'Mobility Recharge', 'Captain’s Conditioning'];
export const workouts: Workout[] = workoutTitles.map((title, i) => ({ id: `w${i + 1}`, title, sport: (['Football', 'Cricket', 'Basketball', 'Running'] as Sport[])[i % 4], minutes: 20 + (i % 5) * 5, level: (['Beginner', 'Intermediate', 'Advanced'] as Level[])[i % 3], focus: ['Speed', 'Power', 'Mobility', 'Conditioning', 'Strength'][i % 5], calories: 160 + i * 12, steps: [{ name: 'Prime the system', seconds: 45, cue: 'Breathe low, move with purpose.' }, { name: drills[(i * 2) % drills.length].name, seconds: 60 + (i % 3) * 30, cue: drills[(i * 2) % drills.length].focus }, { name: drills[(i * 2 + 1) % drills.length].name, seconds: 60 + (i % 4) * 20, cue: drills[(i * 2 + 1) % drills.length].focus }, { name: 'Reset & reflect', seconds: 45, cue: 'Notice one thing that felt sharper.' }] }));
export const challenges = ['Seven-day speed streak', 'Own your warm-up', 'Three clean finishes', 'Early bird miles', 'Strength in consistency', 'Hydration lock-in', 'Recovery is training', 'Footwork fundamentals', 'Power week', 'Team player'];
export const facilities = ['Kinetic Lab Mumbai', 'The Turf Bengaluru', 'Stride House Delhi', 'Arena 21 Pune', 'Elevate Courts Hyderabad', 'Run Club Chennai', 'North Star Strength', 'The Athlete’s Room Jaipur', 'Basecamp Kochi', 'Eastside Performance'];
export const socialPosts: SocialPost[] = Array.from({ length: 20 }, (_, i) => ({ id: `p${i + 1}`, author: ['Aarav Mehta', 'Maya Shah', 'Kabir Rao', 'Ishita Nair', 'Dev Malhotra'][i % 5], handle: ['aarav.m', 'maya.moves', 'kabir.r', 'ishita.run', 'devplays'][i % 5], role: ['Football winger', '100m sprinter', 'Cricket all-rounder', 'Basketball guard', 'Distance runner'][i % 5], initials: ['AM', 'MS', 'KR', 'IN', 'DM'][i % 5], color: ['#e87845', '#008c99', '#d6a72d', '#456a9f', '#4f8a67'][i % 5], text: ['Sharp session today. The last ten percent is where the work lives.', 'New block, same promise: move better than yesterday.', 'Small technical win at training. Saving it here so I repeat it.', 'Recovery walk, proper meal, early night. The boring stuff stacks.', 'Hit a clean personal best and left one in the tank.'][i % 5], time: `${i + 1}h ago`, likes: 18 + i * 7, comments: 2 + (i % 6), tags: ['training', ['football', 'running', 'cricket', 'basketball'][i % 4]] }));
export const matches: Match[] = Array.from({ length: 10 }, (_, i) => ({ id: `m${i + 1}`, teams: '', league: ['National Performance League', 'Athletiq Campus Series', 'City Finals'][i % 3], sport: (['Football', 'Cricket', 'Basketball', 'Running'] as Sport[])[i % 4], time: i < 3 ? `${18 + i}:30 today` : `${i + 8} Jun · ${10 + i}:00`, status: i < 3 ? 'LIVE' : 'UPCOMING', viewers: `${(1.2 + i * .4).toFixed(1)}k`, venue: facilities[i] }));
// Fix the compact seeded team pairing into readable content.
matches.forEach((m, i) => { const pairs = [['Mumbai Strikers', 'Delhi Dynamos'], ['Bengaluru Blazers', 'Pune Pace'], ['Chennai Chargers', 'Kochi Kings'], ['Hyderabad Hawks', 'Jaipur Jaguars']]; m.teams = `${pairs[i % 4][0]}  v  ${pairs[i % 4][1]}`; });

export const defaultGoals: Goal[] = [
  { id: 'g1', title: 'Own my first 10m', metric: '10m sprint', target: 1.7, current: 1.84, unit: 'sec', due: '28 Jun', milestones: [{ label: 'Film baseline', done: true }, { label: 'Two speed sessions weekly', done: true }, { label: 'Break 1.75s', done: false }] },
  { id: 'g2', title: 'Build a weekly rhythm', metric: 'sessions', target: 5, current: 3, unit: 'per week', due: '14 Jun', milestones: [{ label: 'Plan the week', done: true }, { label: 'Train 4 times', done: false }, { label: 'Recover on purpose', done: false }] },
];